-- MySQL Script generated by MySQL Workbench
-- Sun Aug  5 15:47:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `USCODIGO` BIGINT NOT NULL AUTO_INCREMENT,
  `USNOME` VARCHAR(150) NOT NULL,
  `USEMAIL` VARCHAR(100) NULL,
  `USLOGIN` VARCHAR(45) NOT NULL,
  `USSENHA` VARCHAR(128) NOT NULL,
  `USSTATUS` TINYINT NOT NULL DEFAULT 1,
  `USDTCADASTRO` TIMESTAMP NOT NULL,
  `USRGM` CHAR(10) NULL,
  `USIMAGEM` VARCHAR(100) NULL,
  PRIMARY KEY (`USCODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CATEGORIAS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIAS` (
  `CTCODIGO` BIGINT NOT NULL AUTO_INCREMENT,
  `CTDESCRICAO` VARCHAR(45) NOT NULL,
  `CTDTCADASTRO` TIMESTAMP NULL,
  `CTSTATUS` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`CTCODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUTOS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTOS` (
  `PRCODIGO` BIGINT NOT NULL AUTO_INCREMENT,
  `PRNOME` VARCHAR(65) NOT NULL,
  `PRDTCADASTRO` TIMESTAMP NULL,
  `PRSTATUS` TINYINT NULL DEFAULT 1,
  `PRDESCRICAO` LONGTEXT NOT NULL,
  `PRVALOR` DECIMAL(10,2) NULL,
  `PRCTCODIGO` BIGINT NULL,
  PRIMARY KEY (`PRCODIGO`))
ENGINE = InnoDB;

CREATE INDEX `fk_PRODUTOS_CATEGORIAS_idx` ON `mydb`.`PRODUTOS` (`PRCTCODIGO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`IMAGENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IMAGENS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`IMAGENS` (
  `IMCODIGO` BIGINT NOT NULL AUTO_INCREMENT,
  `IMTITLE` VARCHAR(45) NULL,
  `IMHREF` VARCHAR(100) NOT NULL,
  `IMSTATUS` TINYINT NULL DEFAULT 1,
  `IMDTCADASTRO` TIMESTAMP NULL,
  `IMPRCODIGO` BIGINT NULL,
  PRIMARY KEY (`IMCODIGO`))
ENGINE = InnoDB;

CREATE INDEX `fk_IMAGENS_PRODUTOS1_idx` ON `mydb`.`IMAGENS` (`IMPRCODIGO` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
